repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.0
    hooks:
      - id: gitleaks
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - '--args=--lockfile=false'
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
          - '--args=--only=terraform_unused_required_providers'
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
          - --tf-init-args=-upgrade
-   repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.219'
    hooks:
      - id: checkov
        verbose: true
        args: [
          --compact,
          --download-external-modules,"true",
          --quiet,
          --soft-fail,
          --skip-check, "CKV_AZURE_33,CKV_AZURE_42,CKV_AZURE_43,CKV_AZURE_110,CKV_AZURE_112,CKV2_AZURE_1,CKV2_AZURE_40"
        ]
-   repo: https://github.com/tenable/terrascan
    rev: v1.19.1
    hooks:
      - id: terraform-pre-commit
        args: [ '-i terraform --non-recursive' ]
        files: ^.*\.tf$
        exclude: ^\.github/.*
